sent = "abcdefgabc "
print("str : {}".format(sent))
sent = sent.strip()
print("str.strip() : {}".format(sent))
print("len(str) : {}".format(len(sent)))
print("str.count('b') : {}".format(sent.count('b')))
print("str.find('b') : {}".format(sent.find('b')))
print("str.index('b') : {}".format(sent.index('b')))
print("str.isupper() : {}".format(sent.isupper()))
print("str.islower() : {}".format(sent.islower()))
print("str.isalpha() : {}".format(sent.isalpha()))
print("str.isdigit() : {}".format(sent.isdigit()))
print("str.isalnum() : {}".format(sent.isalnum()))
print("str.upper() : {}".format(sent.upper()))
print("str.lower() : {}".format(sent.lower()))
sent = sent.replace('d', 'z')
print("str.replace('d','z') : {}".format(sent))
sent = ','.join(sent)
print("','.join(str) : {}".format(sent))
sent = sent.split(',')
print("str.split(',') : {}".format(sent))